### ISSUE TITLE
merge branches of schema

### ISSUE THREAD

**Issue by holfordm** [bodleian/consolidated-tei-schema#10]
just creating an issue for this so it doesn't get lost - hope that's ok!

**Comment by andrew-morrison** [comment]
I have merged the branches. You might need to close and reopen Oxygen to clear its temporary cache.

I have a few questions:

1. All but one of your schematron rules is set up to be specific to Medieval. But the `@key` attributes ones would be good for every catalogue that wants the corresponding indexes on their web sites. The `supportDesc/@material` requirement is universally adhered to in all but a single manuscript in all the catalogues. The requirement to have a `textLang` in every `msContents` is more debatable, I guess, but could certainly be a recommendation. So, would you have any objection to making them generic, but with a role of "warn"?
2. The .rng was build back in October, so includes the changes in version 3.2.0 of TEI P5. But there is a new [version 3.3.0](http://www.tei-c.org/release/doc/tei-p5-doc/readme-3.3.0.html) which was released last week. Whose job is it to review the changes and rebuild? Or is that not considered necessary for this project?
3. Do you want to keep the medieval-schematron branch?

**Comment by ahankinson** [comment]
I think it would be our responsibility to steward upgrades to the TEI schema and make sure it doesn't break anything.

**Comment by holfordm** [comment]
I don't have any objections to making the schematron rules generic (and I can think of others we might add...) but maybe check with the other catalogue owners first in case the sudden appearance of red squares alarms them?
I suppose that updating the ODD (if that is necessary) and rebuilding the .rng after TEI updates should be the responsibility of the "owner" of the consolidated-tei schema, whoever that may be (? @andrew-morrison ?)
No need to keep the medieval-schematron branch

**Comment by andrew-morrison** [comment]
The sudden appearance of red squares is why I suggested giving those schematron rules a role of "warn". Then they'd be displayed as yellow triangles (when validating in Oxygen) instead. It also helps triage to have more than one level (e.g. the lack of a `@key` is something you'd want to fix, but not before tackling invalid TEI.) 

I'll review TEI releases from now on, for things that might suddenly become invalid. I don't have time to do so for 3.3.0 now, but maybe next month.

**Comment by holfordm** [comment]
Thanks for clarifying. Sounds like we are good to go ahead with this then. Can I suggest an additional rule now which is that origdate should always have one or more of the relevant dating attributes?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
