### ISSUE TITLE
New schematron rule: origDate 

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/consolidated-tei-schema#11]
Each `origDate` should always have one or more of the relevant dating attributes: `@when, @notBefore, @notAfter, @from or @to`. And a `@calendar`?

Probably a "warn" level rule.

Suggested in  #10

**Comment by holfordm** [comment]
I don't think `@calendar` is needed if it is Gregorian. Actually there are probably some unresolved issues around Gregorian / Julian dating...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by andrew-morrison** [comment]
This was done in the previous release.
