### ISSUE TITLE
problem with `subst` element?

### ISSUE THREAD

**Issue by holfordm** [bodleian/consolidated-tei-schema#14]
I get a validation error if I try to use the `<subst>` element, which is a standard part of the transcr module, probably useful to all the catalogues for transcribing incipits, explicits, rubrics, etc. - is this an issue with our ODD? (it seems to validate fine in a standard TEI document in Oxygen)

**Comment by ahankinson** [comment]
I suspect it's because of this:

https://github.com/bodleian/consolidated-tei-schema/blob/master/msdesc.odd#L102-L109

**Comment by ahankinson** [comment]
@andrew-morrison I can run you through the process of editing and generating a new RNG from the TEI ODD if you like. It can be a bit tricky...

**Comment by holfordm** [comment]
We will need to add a template for this element in convert2HTML as well
