### ISSUE TITLE
Review of schema elements

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/consolidated-tei-schema#22]
In #21, I've done a quick tidy up of the schema, trimming a few elements and adding a couple. This was to fix a couple of gaps, remove some elements that aren't used (or just once or twice, and incorrectly), and reduce complexity to allow for more concise documentation to be written.

But longer-term we may want to allow more elements for marking up transcription, so that more details can be recorded in notes, incipits, rubrics, etc. I do not think including the whole transcription module would be a good idea, because it contains elements which only make sense in full transcriptions. Also any additions will require development time to display them correctly on the web sites. Here are some candidates:

- [handNotes](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/handNotes)
- [handShift](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/handShift)
- [mod](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/mod)
- [redo](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/redo)
- [restore](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/restore)
- [secl](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/secl)
- [space](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/space)
- [surplus](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/surplus)

Also, the following elements are already in our schema, but not yet used. Should any be removed?

- [am](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-am)
- [authority](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-authority)
- [cit](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-cit)
- [district](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-district)
- [geogFeat](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-geogFeat) (a child of geogName, which has been used, although incorrectly)
- [lg](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-lg)
- [licence](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-licence)
- [msFrag](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msFrag)
- [msItemStruct](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-msItemStruct) (there's no reason to use this over msItem in a new description, but someone might come along with legacy data which uses it) 
- [objectType](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-objectType)
- [orig](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-orig)
- [projectDesc](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-projectDesc)
- [reg](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-reg)
- [relatedItem](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-relatedItem)
- [scriptDesc](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-scriptDesc)
- [scriptNote](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-scriptNote)
- [surfaceGrp](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-surfaceGrp) (for grouping surface element, which have been used, although a lot of the time incorrectly retained when someone re-used someone else's template) 
- [sponsor](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-sponsor)
- [typeDesc](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-typeDesc)
- [zone](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-zone) (child of surface)

Please give feedback on the above, or make other suggestions, and I'll look to update the schema in November/December.

**Comment by bequessel** [comment]
I am not sure if this should be its own new issue; I want to suggest the inclusion of two further elements in the schema, i.e. (1) **fw** in the _transcr_ module, (to add detailed markup of catchwords or specific features of the original pagination in Oriental manuscripts)  and (2) **geo** in the _namesdate_ module (e.g. used inside history/origin/origin/p/origPlace to geographical data from the International Dunhuang Project legacy database).
The British Library intends to replace its present ENRICH like schema with the consolidated schema and, as far as I can see, only these two elements would be required to make this possible.

**Comment by jamescummings** [comment]
Just to note that the brief when given to me was not to cater for transcription (thus only bare minimum of transcriptional elements). The ones you suggest seem reasonable. 

I'd hold on to those unused ones personally ... we wanted to be fairly loose for potential future development. 

@bequessel's suggestions completely reasonable as well. 

I had a question from someone else about updating their ENRICH schema (since things have changed so much from when we created it) today in a coincidence. Maybe there should be a big EU project to update it.  Coming out in a couple weeks in next release of TEI Guidelines will be our first stab at object descriptions with the `<object>` element. These are at the moment based entirely on manuscript description and will slowly be generalised.

**Comment by andrew-morrison** [comment]
@bequessel: We can add `fw` and `geo`. Selection of elements is controlled in the same file ([the ODD](http://www.tei-c.org/guidelines/customization/getting-started-with-p5-odds/)) that contains the documentation. We have been working on that recently, and [a draft is here](https://bodleian.github.io/consolidated-tei-schema/msdesc.html). If you could provide a sentence or two on how each of these elements might be used in a manuscript description context, and maybe an example of each if you have got them, then we could add that at the same time.

@jamescummings: Thank you for the information.

**Comment by bequessel** [comment]
we are using **fw** mainly to provide information on the original pagination or running signatures on a manuscript or blockprint. e.g.
```
<foliation\>
<p\>
<fw place="left" type="pag" xml:lang="bo"/><!--has pagination in Tibetan-->
<fw type="sig" place="left" xml:lang="bo">ཁི</fw>
</p>
</foliation>
```
**geo** we use to accomodate geodata (e.g. legacy data from a International Dunhuang Project database table), this example indicates the location of the place of origin, here the location of subsite 17 of the Dunhuang Mogao excavation site:
```
<origin notBefore="0750" notAfter="1000">
<p>
<origPlace>DHMG.(Dunhuang Mogao) DHMG.17.<geo n="min">94.80388888888889198  40.03638888888888658</geo><geo n="max">95.9375 40.04833333333333201</geo>
</origPlace>
</p>
</origin>`
```

**Comment by bequessel** [comment]
apologies for the wrong closing tags in the fist bit  of code. I am only just getting used to markdown.

**Comment by ahankinson** [comment]
No problem -- I've tidied it up for you.

**Comment by jamescummings** [comment]
From memory if you want syntax highlighted xml blocks do 3 tildes followed by the word xml (no space) and end with three tildes.   E.g.

~~~xml
<foo blort="wibble">
   Some thing <marked blort="foo">else </marked>.
</foo>
~~~

Hope that helps.

**Comment by andrew-morrison** [comment]
There is a [new release](https://github.com/bodleian/consolidated-tei-schema/releases) which includes the addition of `fw` and `geo`.

Otherwise, I haven't added any of the elements suggested in my original post, as there has been no interest expressed. So I'll close this issue now.

@bequessel: You also requested an XML Schema version. I added that (and a DTD) back in October, but I cannot remember whether I informed you at that time. Anyway, these are now up-to-date and [available here](https://github.com/bodleian/consolidated-tei-schema/tree/master/alternatives).

**Comment by bequessel** [comment]
very much appreciated. I ran into some error messages while trying to use the schema files (both rng and xsd) in a validation scenario in Oxygen. Am I missing something?

with xsd:
![msdesc_xsd](https://user-images.githubusercontent.com/41159363/52945455-ac7d8280-3369-11e9-9f1b-283df48a556f.png)

with rng:
![msdesc_rng 1](https://user-images.githubusercontent.com/41159363/52945489-bf905280-3369-11e9-8e29-ef3fadf321a1.png)

**Comment by andrew-morrison** [comment]
Those error messages look like you pointed Oxygen at, or downloaded from, the GitHub pages for the schema files, not the files themselves.

For example, if you go to https://github.com/bodleian/consolidated-tei-schema/blob/master/alternatives/msdesc.xsd it will display the XSD but you need to click on the "Raw" button. That takes you to https://raw.githubusercontent.com/bodleian/consolidated-tei-schema/master/alternatives/msdesc.xsd which is what you need to use when validating. I've added something to make this clearer in the readme file in the alternatives folder.

If you do download, the XSD is split into multiple files, so you need to download them all.

**Comment by bequessel** [comment]
you were, of course, right. Stupid me.  Validation works a treat now. Thanks again.
