### ISSUE TITLE
adding documentation to the ODD

### ISSUE THREAD

**Issue by holfordm** [bodleian/consolidated-tei-schema#23]
I've created a new branch for this repository with a version of the ODD that contains some documentation (still draft) for the medieval catalogue, and an html output of that ODD (generated with ROMA). 

@ahankinson @andrew-morrison this can be merged with the main branch if you are happy with the changes.

the other catalogues should be encouraged to write their own documentation and add it eventually to this file; presumably we would want one `div` with common practices for all catalogues, followed by separate `div`s for the separate catalogues.

The html output unfortunately doesn't display in GitHub, so we might think about hosting it elsewhere (the wiki?); we could generate a PDF from ROMA to display here

**Comment by andrew-morrison** [comment]
I've made some changes, please take a look:

https://github.com/bodleian/consolidated-tei-schema/commit/24c058337cab886706ab1efecff8d991fdc4d3c3

Also I've set up this repository so anything in its _docs_ folder will be made available via a URL beginning with `https://bodleian.github.io/consolidated-tei-schema/`. Unlike the "raw" file view, that will send out the correct MIME types to tell web browsers how to display each file, so HTML should display correctly in the browser. But only what is on the master branch, so the add-documentation branch will need to be merged into master before it will work.

**Comment by andrew-morrison** [comment]
I've made some more changes and tested the schematron rules on other catalogues:

69c73500456c660174568aa9491496bb536924b1
d2e1c03dc54faea4630292807c9535f66e417d3f

@holfordm: If you're happy with these, and want to publish the documentation (the HTML will be available at https://bodleian.github.io/consolidated-tei-schema/msdesc.html), please go ahead and merge the add-documentation branch into master.

**Comment by andrew-morrison** [comment]
Improving the documentation is an ongoing task, so I'll close this issue.
