### ISSUE TITLE
display of attributes in html /pdf output of ODD

### ISSUE THREAD

**Issue by holfordm** [bodleian/consolidated-tei-schema#28]
Attributes and their values (ie. text enclosed in the `att` or `val` tags in the ODD) is not typographically distinguished in the HTML output (or for that matter in the PDF). Presumably this is an issue with the TEI stylesheets that carry out the conversion, if so should it be raised as an issue on the TEI Github site, and is there anything we can do about it meanwhile?

**Comment by andrew-morrison** [comment]
I think I just need to copy one CSS file from the original documentation. But the TEI-C seem to have been having some trouble with the web servers since Friday:

https://twitter.com/TEIconsortium
