### ISSUE TITLE
Allow customised manuscript HTML for each TEI catalogue

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/consolidated-tei-schema#4]
Move convert2HTML.xsl for generating HTML for manuscript pages out of the medieval-mss repository, into consolidated-tei-schema, and create a stub XSLT stylesheet in each of the TEI catalogue repositories, which then imports the central one.

There seems to be a few obviously Medieval-specific things already in the XSLT, which will need moving out and possibly a generic replacement created.

This will provide the option for customisation (but no necessity to do so.) The import href will have to be a URL, meaning processing and previewing in Oxygen won't be possible offline, or if github goes down, but then the schema is already accessed via a raw.githubusercontent.com URL.

**Comment by holfordm** [comment]
This is a good idea in theory, but it assumes more similarity than difference between the data in the different catalogues, and the output they require. Do we need to assess these issues before proceeding? Otherwise it may end up introducing more complexity than it removes. @eifionjones will be working on the Fihrist version of convert2html, so perhaps he could report back on this?


________________________________

**Comment by ahankinson** [comment]
I'm keen on making sure we have as little customised behaviour between the catalogues as possible, since it will be easier for us to fix issues and make improvements if we can do that centrally, rather than have 10 different XSLTs that we need to update with the same fix.

I think @andrew-morrison has a solution where we can import the 'central' XSLT, whose behaviour can be overridden by local rules as necessary. This seems to me to be a solution that provides the most amount of flexibility while still ensuring we can support improvements across all catalogues.

**Comment by andrew-morrison** [comment]
Here is a random example of a British Library manuscript, first how it appears currently on the Fihrist QA site, with fields determined by Blacklight...

![blacklight_default_fields](https://user-images.githubusercontent.com/33721187/33128318-ee2b890c-cf83-11e7-8742-9715ee7d951b.jpg)

...and below is a screenshot of the result of running the TEI through an XSLT stylesheet that just imports the Medieval convert2HTML.xsl and wraps whatever its templates output in html and body tags (plus the CSS from Medieval's live site)...

![transformed_by_convert2html](https://user-images.githubusercontent.com/33721187/33127878-401d9068-cf82-11e7-9346-7ea1204eb462.jpg)

...obviously, the links don't work.

I don't really have a good idea what kind of customizations might be desirable. Say if Fihrist want 'History' first, followed by 'Contents', then @eifionjones could write a new template to match msDesc that imposes an order (because Medieval appear to just follow the ordering in the TEI), and put that in their convert2HTML.xsl, and it would override. Pretty simple, self-explanatory, and unlikely to cause issues going forward. But if they want the dimensions handled as [on their current web site](http://www.fihrist.org.uk/profile/manuscript/3fec9556-1594-43c8-901c-bf0b8d6beac8), in a HTML table and without the 'written' field, that would require overriding a couple of templates, and maybe some UX work on the CSS.

**Comment by ahankinson** [comment]
I think it would be worthwhile trying this with a larger Fihrist MSS as well, since that's when the difference between the Blacklight display and the TEI HTML display will become apparent.

Following the TEI order is a good default behaviour. Was ordering specifically mentioned as an issue with the Fihrist data?

**Comment by eifionjones** [comment]
I think we'd definitely want Fihrist to be as standard as possible here, including following TEI ordering. I'll take a look at the xslt with some of our records and see how they look. My impression is that people will just be happy to be able to see the full information!

**Comment by andrew-morrison** [comment]
I've added two new XSLT files to the fihrist-mss repository's processing folder:

- [convert2HTML.xsl](https://github.com/bodleian/fihrist-mss/blob/master/processing/convert2HTML.xsl): Does nothing except import Medieval's convert2HTML.xsl
- [previewManuscript.xsl](https://github.com/bodleian/fihrist-mss/blob/master/processing/previewManuscript.xsl): Import the local convert2HTML.xsl and wraps whatever it outputs in html and body tags, adding CSS, for people previewing as they edit the TEI in Oxygen.

@eifionjones: If you want to try this out, maybe add some customizations to this new Fihrist convert2HTML.xsl if you find something that does need it, and let us know how it goes. Then, if this looks like it'll work, I can set everyone up with the same, only importing from a common XSL rather than Medieval's copy of convert2HTML.xsl (and I'll rename the common one to something else so it's less confusing.)

**Comment by ahankinson** [comment]
Can we point to a copy of the XSLT in this repo, instead of the Medieval one?

**Comment by andrew-morrison** [comment]
Just to clarify, this is temporary. I'll point all, including Medieval and Fihrist, to a copy of the XSLT which I'll move to this repository once we're all happy this method of allowing (minimal) customization will work.

**Comment by andrew-morrison** [comment]
Sorry, I've realised that importing one stylesheet into another causes a problem when run by generate-html.sh, because the original convert2HTML.xsl goes looking for TEI files based on a path relative to itself (the XSLT stylesheet), which won't be correct when that's imported from a different repository (and via a URL.)

I think the only way around it is to modify generate-html.sh to specify the path to the TEI files as a parameter. I'll set that up tomorrow morning.

**Comment by ahankinson** [comment]
That would be fine -- the `generate-html.sh` script is a convenience that can be amended as needed.

**Comment by andrew-morrison** [comment]
It's taken me a while to remember the secret sauce to get around this problem (which is to prefix 'file://' to force the use of a local path) but it's now working.

The 'processing' folder in Fihrist now has a generate-html.sh. Running this will batch convert all TEI in the collections folder into HTML in a 'html' subfolder of 'processing' which it creates (maybe not ideal as this is within the local git repository, so will show up as thousands of untracked files along with any new TEI anyone might have created.)

Also perhaps a Windows-equivalent shell script is needed, if other people are going to run it, say when Huw is on holiday? They'll have the Saxon XSLT processor if they've got Oxygen, but it also uses a tool called "tidy" to convert the almost-HTML output by the XSL into full HTML - I'm not sure why that can't be done in the XSL - which most won't have or know how to install.

**Comment by holfordm** [comment]
I have taken a copy of previewManuscript.xsl into the medieval-mss/processing folder since it will be extremely useful there as well especially as we bring colleges into TEI cataloguing

**Comment by andrew-morrison** [comment]
@holfordm: Are you happy for me to switch Medieval over to using a convert2HTML.xsl that imports all the actual code to generate the manuscript HTML view from a consolidated XSL stylesheet common for everyone, with the option to override if necessary?

I've reviewed that XSLT, not changing the functionality, but modifying it to make any such customization easier (basically splitting any templates that contained lots of logic into separate templates which can be overridden individually.) I noticed a few potential problems (e.g. inconsistency in outputting an "Extent:" label) which I could now fix, [and whichever of the issues recorded here](https://github.com/bodleian/medieval-mss/issues) are still relevant, once the code is all in one place.

**Comment by holfordm** [comment]
Yes, please go ahead with this

**Comment by andrew-morrison** [comment]
I did the switch over this morning. Medieval's convert2HTML.xsl now imports all the actual templates for transforming TEI to HTML from [msdesc2html.xsl here](https://github.com/bodleian/consolidated-tei-schema/blob/master/msdesc2html.xsl) just like Fihrist. 

Any fixes for issues that seem likely to be applicable to all TEI catalogues (e.g. [multiple "Record Sources" headings](https://github.com/bodleian/medieval-mss/issues/98)) will be fixed in msdesc2html.xsl from now on. That does mean issues raised in the medieval-mss repository (or the fihrist-mss one) will likely be fixed by commits to the consolidated-tei-schema repository. Please bear with me while I experiment with GitHub's ability to link across repositories.

The next step is to set up the Fihrist QA site to display HTML for manuscripts. I've created an issue over in that repository for that (bodleian/fihrist-mss#15) so I'm closing this one as I think I've done all I can to permit sharing and customizing the HTML view between catalogues, and if does turn out to be impractical it would be easy to split them.
