### ISSUE TITLE
Remove dependency on tidy command to generate manuscript XHTML that Blacklight can use

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/consolidated-tei-schema#5]
Not everyone who might need to run the generate-html.sh script will have, or know how to install, the [tidy tool](http://www.html-tidy.org/). It should be possible to modify the XSLT so that it isn't necessary.

**Comment by andrew-morrison** [comment]
The tidy command as currently configured in generate-html·sh does the following:

- Ensures no DOCTYPE declaration
- Converts named entity references to numeric
- Applies its own indenting
- Wraps text at 160 chars per line
- Ensures "well-formed XHTML"
- Converts to UTF-8

It doesn't (and can't) ensure the XTHML is valid, as that is for us to sort out (e.g. currently some uses of bibl end up with a div instead of an li inside a ul.)

All except wrapping at 160 chars should be possible in XSLT. Technically entity references are handled by Saxon, which will convert them to UTF-8 characters before the XSLT is applied, leaving just the ones for angle brackets and ampersands, which shouldn't cause issues. Really neat indenting would require a second XSLT transformation, of the HTML into neater HTML, which could be done inside the same stylesheet by temporarily storing a result tree fragment, but even that would be better than relying on the tidy tool.

@ahankinson: Do you recall what in particular caused trouble for Blacklight before tidy was used?

**Comment by ahankinson** [comment]
It was a generic "fix messy HTML" step that I implemented, primarily so that I could look at the HTML output that was being generated to try and fix things in the XSLT. I don't think it caused problems for Blacklight -- mostly problems with me. :)

**Comment by andrew-morrison** [comment]
Note: An earlier commit made the corresponding Bash script changes, and also likewise modified the XQuery to remove the need for xmllint. But those changes are in the medieval-mss repository, not this one, as those scripts are Medieval-specific (for now) and will probably be cloned and modified for each TEI catalogue.
